#!/usr/bin/env python3
"""
mkenga.py <in main.c> <out main.c> -- turn an Engine B (sub screen) GX fixture into the same
scene on Engine A (main screen), for gx-next-steps-log.md task 13.

The Engine B fixtures (affinerom / fxrom / cirom) drive the SUB engine and leave the MAIN
engine on a flat backdrop. This swaps the two: every sub-engine register / palette / OAM /
VRAM-bank reference becomes its main-engine counterpart and the (flat) main-engine setup
becomes the sub engine's. Mapping (all whole-identifier or exact-literal, so a leftover would
fail to compile or show up as an obviously wrong picture):

  0x06200000 (BBG, bank C)   -> 0x06000000 (ABG,  bank A)
  0x06600000 (BOBJ, bank D)  -> 0x06400000 (AOBJ, bank B)
  0x07000400 (sub OAM)       -> 0x07000000 (main OAM)
  0x04001xxx (sub regs)      -> 0x04000xxx (main regs)
  0x06898000 (bank H LCDC)   -> 0x06880000 (bank E LCDC)   ext BG palette: H(32K) -> E(64K, first 32K used)
  VRAM_I ext OBJ palette     -> bank F (16K)
  REG_*_SUB, *_PALETTE_SUB, oamSub, videoSetModeSub  <-> their main-engine names
"""
import re, sys

src = open(sys.argv[1]).read()

# 1. protect the ORIGINAL main-engine (flat backdrop) names by moving them to the sub names
#    via placeholders, then swap.
def swap(s, a, b):
    return s.replace(a, "\x00A\x00").replace(b, a).replace("\x00A\x00", b)

s = src
# videoSetMode <-> videoSetModeSub (function-call form only)
s = re.sub(r"\bvideoSetModeSub\(", "\x00VSMS\x00(", s)
s = re.sub(r"\bvideoSetMode\(", "videoSetModeSub(", s)
s = s.replace("\x00VSMS\x00(", "videoSetMode(")
# BG_PALETTE[ (main, non-suffixed) <-> BG_PALETTE_SUB[
s = s.replace("BG_PALETTE_SUB", "\x00BGP\x00")
s = re.sub(r"\bBG_PALETTE\b", "BG_PALETTE_SUB", s)
s = s.replace("\x00BGP\x00", "BG_PALETTE")
s = s.replace("SPRITE_PALETTE_SUB", "SPRITE_PALETTE")
# REG_xxx_SUB -> REG_xxx (the fixtures never touch the main-engine REG_xxx forms except REG_VCOUNT)
s = re.sub(r"\bREG_([A-Z0-9]+)_SUB\b", r"REG_\1", s)
s = re.sub(r"\boamSub\b", "oamMain", s)
# literals
s = s.replace("0x06200000", "0x06000000").replace("0x06600000", "0x06400000")
s = s.replace("0x07000400", "0x07000000")
s = re.sub(r"0x04001([0-9A-Fa-f]{3})", r"0x04000\1", s)
s = s.replace("0x06898000", "0x06880000")
# VRAM banks
s = s.replace("vramSetBankC(VRAM_C_SUB_BG)", "vramSetBankA(VRAM_A_MAIN_BG)")
s = s.replace("vramSetBankD(VRAM_D_SUB_SPRITE)", "vramSetBankB(VRAM_B_MAIN_SPRITE)")
s = s.replace("vramSetBankH(VRAM_H_LCD)", "vramSetBankE(VRAM_E_LCD)")
s = s.replace("vramSetBankH(VRAM_H_SUB_BG_EXT_PALETTE)", "vramSetBankE(VRAM_E_BG_EXT_PALETTE)")
s = s.replace("vramSetBankI(VRAM_I_LCD)", "vramSetBankF(VRAM_F_LCD)")
s = s.replace("vramSetBankI(VRAM_I_SUB_SPRITE_EXT_PALETTE)", "vramSetBankF(VRAM_F_SPRITE_EXT_PALETTE)")
s = re.sub(r"\bVRAM_H\b", "VRAM_E", s)
s = re.sub(r"\bVRAM_I\b", "VRAM_F", s)
s = s.replace("bank H", "bank E").replace("bank I", "bank F")
hdr = "// GENERATED by tools/vsd-testrom/mkenga.py from the Engine B fixture -- DO NOT EDIT (Engine A copy).\n"
open(sys.argv[2], "w").write(hdr + s)
